// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl6CosGg_xWILl11PTd4WwM6PYBNVXzZ0',
    appId: '1:730865469147:web:7955b3b8b9805db5aeeefe',
    messagingSenderId: '730865469147',
    projectId: 'asroo-shop-getx-e74ab',
    authDomain: 'asroo-shop-getx-e74ab.firebaseapp.com',
    storageBucket: 'asroo-shop-getx-e74ab.appspot.com',
    measurementId: 'G-WK4MMDTQJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZxpQLMZbnJAm88q0iIPlUaFfHz89EWL0',
    appId: '1:730865469147:android:afd1e743cfedfb80aeeefe',
    messagingSenderId: '730865469147',
    projectId: 'asroo-shop-getx-e74ab',
    storageBucket: 'asroo-shop-getx-e74ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3TViNQqJVJeNTaqfupjeqe2vppdI2VZ4',
    appId: '1:730865469147:ios:3a160864104d436daeeefe',
    messagingSenderId: '730865469147',
    projectId: 'asroo-shop-getx-e74ab',
    storageBucket: 'asroo-shop-getx-e74ab.appspot.com',
    iosBundleId: 'com.example.ecommerceWithMvc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3TViNQqJVJeNTaqfupjeqe2vppdI2VZ4',
    appId: '1:730865469147:ios:3a160864104d436daeeefe',
    messagingSenderId: '730865469147',
    projectId: 'asroo-shop-getx-e74ab',
    storageBucket: 'asroo-shop-getx-e74ab.appspot.com',
    iosBundleId: 'com.example.ecommerceWithMvc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl6CosGg_xWILl11PTd4WwM6PYBNVXzZ0',
    appId: '1:730865469147:web:f519956eeff70059aeeefe',
    messagingSenderId: '730865469147',
    projectId: 'asroo-shop-getx-e74ab',
    authDomain: 'asroo-shop-getx-e74ab.firebaseapp.com',
    storageBucket: 'asroo-shop-getx-e74ab.appspot.com',
    measurementId: 'G-MFQWR07TGQ',
  );
}
